### ISSUE TITLE
Missing command in v1.28.0

### ISSUE THREAD

**Issue by sukha-cn** [TomasHubelbauer/vscode-markdown-todo#2]
![image](https://user-images.githubusercontent.com/9590083/46654890-8cc89780-cbdc-11e8-98d4-c97162ad00e4.png)

I installed this plugin with version v11.0. 
The vscode version is v1.28.0

It works well, but I think "missing command" is not normal. 

Hope it will be better.

**Comment by TomasHubelbauer** [comment]
Hey, thank you, I will fix this ASAP.

**Comment by ChadBailey** [comment]
Unfortunately, also impacted...

I thought it was another extension that was incompatible, but I have removed most and disabled the others with no impact.

![image](https://user-images.githubusercontent.com/15102816/73503078-c3599100-4390-11ea-977f-f872f22f1fb3.png)

**Comment by TomasHubelbauer** [comment]
Thanks! I haven't had much time to dedicate to my VS Code extensions lately, but this is pretty serious so I'll do my best to fix this up. Thanks everyone for reporting!

**Comment by gustavodipietrodeus** [comment]
Any update? The plugin is still unusable atm

**Comment by TomasHubelbauer** [comment]
Yeah, I agree with you, but it looks like I won't be able to take a look at this after all. If you or anyone could take a look and see what's up, I'd be grateful, but not that the code in master is likely in a WIP state so you'll have to check out the commit which corresponds to the last release date. I am working on different things right now and this extension (and my other ones) are essentially abandoned as a result, so I'm sorry for that, but I don't think it will be changing before I have more free time on my hands.

**Comment by machineghost** [comment]
I don't know VS Code extensions at all, but could this be caused by line 470 of https://github.com/TomasHubelbauer/vscode-markdown-todo/blob/6250675e1f3a1f42aff2a5a24648f1ad8988d9db/src/extension.ts?

    lenses.push(new TodoCodeLens(line.range, document.uri.fsPath));

The other code lenses are showing up fine, but that one doesn't, and it's added just before the other ones ... exactly where the "MISSING: command" bit is.

**Comment by TomasHubelbauer** [comment]
The thing I have been putting off is recovering/recreating the access token used for publishing the extensions. I've sorted that now so I will try to see if publishing works as expected on another less valuable extension of mine and when I've verified that, I'll roll back the source code to the version that is currently live (I think I've dropped the ball on this project in a middle of a WIP change) and will apply the change you speak of. Then I'll cut a new release. I'll keep this thread updated on when I've done that.

**Comment by hendrik-scholz** [comment]
@machineghost Thanks for the tip. I removed the line you mentioned, built the extension on my computer, and installed the package manually. After that, the message was gone.

See https://code.visualstudio.com/api/working-with-extensions/publishing-extension and https://medium.com/@sanik.bajracharya/vscode-how-to-create-your-own-extension-pack-483385644c29 on how to build and install an extension.

**Comment by TomasHubelbauer** [comment]
I have at least commented out the line in `master` so that people can just build it without needing to change anything. I am trying to get tests and CI to work now and then I'll finally publish the new version.

**Comment by TomasHubelbauer** [comment]
Alright, folks, we did it!

https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-todo

This bug is fixed in version 12 which has just gone live! Please, update and report any issues you might find. I have not touched any of my extensions for a long time, so it's very possible that I've borked something.

Also, apologies to all of you who have been waiting for this. This took me like 30 minutes inclusive of ditching Travis, setting up GitHub Actions and relogging to VSCE, so I don't know why I was putting this off so hard. Good news is getting this finally done is very rejuvenating so I'm hoping to continue improving this extensions and not let it go stale again.
